version: '3.7'

networks:
  test:
    name: carlife

services:
  ca_tls:
    image: hyperledger/fabric-ca:latest
    labels:
      service: hyperledger-fabric
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-tls
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=17050
      - FABRIC_CA_SERVER_OPERATIONS_LISTENADDRESS=0.0.0.0:18050
    ports:
      - "17050:17050"
      - "18050:18050"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ../organizations/fabric-ca/tls:/etc/hyperledger/fabric-ca-server
    container_name: ca_tls
    networks:
      - carlife

  ca_component_supplier:
    image: hyperledger/fabric-ca:latest
    labels:
      service: hyperledger-fabric
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-component_supplier
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=17051
      - FABRIC_CA_SERVER_OPERATIONS_LISTENADDRESS=0.0.0.0:18051
    ports:
      - "17051:17051"
      - "18051:18051"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ../organizations/fabric-ca/component_supplier:/etc/hyperledger/fabric-ca-server
    container_name: ca_component_supplier
    networks:
      - carlife

  ca_manufacturer:
    image: hyperledger/fabric-ca:latest
    labels:
      service: hyperledger-fabric
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-manufacturer
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=17052
      - FABRIC_CA_SERVER_OPERATIONS_LISTENADDRESS=0.0.0.0:18052
    ports:
      - "17052:17052"
      - "18052:18052"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ../organizations/fabric-ca/manufacturer:/etc/hyperledger/fabric-ca-server
    container_name: ca_manufacturer
    networks:
      - carlife

  ca_store:
    image: hyperledger/fabric-ca:latest
    labels:
      service: hyperledger-fabric
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-store
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=17053
      - FABRIC_CA_SERVER_OPERATIONS_LISTENADDRESS=0.0.0.0:18053
    ports:
      - "17053:17053"
      - "18053:18053"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ../organizations/fabric-ca/store:/etc/hyperledger/fabric-ca-server
    container_name: ca_store
    networks:
      - carlife
  
  ca_insurer:
    image: hyperledger/fabric-ca:latest
    labels:
      service: hyperledger-fabric
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-insurer
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=17054
      - FABRIC_CA_SERVER_OPERATIONS_LISTENADDRESS=0.0.0.0:18054
    ports:
      - "17054:17054"
      - "18054:18054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ../organizations/fabric-ca/insurer:/etc/hyperledger/fabric-ca-server
    container_name: ca_insurer
    networks:
      - carlife

  ca_maintenancer:
    image: hyperledger/fabric-ca:latest
    labels:
      service: hyperledger-fabric
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-maintenancer
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=17055
      - FABRIC_CA_SERVER_OPERATIONS_LISTENADDRESS=0.0.0.0:18055
    ports:
      - "17055:17055"
      - "18055:18055"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ../organizations/fabric-ca/maintenancer:/etc/hyperledger/fabric-ca-server
    container_name: ca_maintenancer
    networks:
      - carlife
  
  ca_consumer:
    image: hyperledger/fabric-ca:latest
    labels:
      service: hyperledger-fabric
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-consumer
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=17056
      - FABRIC_CA_SERVER_OPERATIONS_LISTENADDRESS=0.0.0.0:18056
    ports:
      - "17056:17056"
      - "18056:18056"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ../organizations/fabric-ca/consumer:/etc/hyperledger/fabric-ca-server
    container_name: ca_consumer
    networks:
      - carlife